# Generated by Django 4.2.1 on 2023-05-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Acive', 'Acive'), ('Inacive', 'Inacive')], max_length=20, null=True),
        ),
    ]
